name: Verificar secretos con python

on: 
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content #Descarga de repositorio en $GITHUB_WORKSPACE
        uses: actions/checkout@v4
        
        # TODO - Instalar python (buscar action e incorporarla) + ejecutar script del mismo modo que hemos hecho el hola mundo