name: Verificar secretos con python

on: 
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup pythondevelop
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # el action recibe la versión. Como saberlo?  https://github.com/actions, https://github.com/actions/setup-python

      - name: Instalación de dependencias
        run: |
          python -m pip install --upgrade pip

      - name: Ejecución script # ejecuta secret_finder.py para buscar la palabra reservada password
        run: python $GITHUB_WORKSPACE/.github/workflows/scripts/secret_finder_v2.py $GITHUB_WORKSPACE/app/src password
