# Cuenta gratuita para estudiantes, no necesario tarjeta: https://azure.microsoft.com/es-es/free/students
# Azure App Service: https://azure.microsoft.com/es-es/products/app-service/
# Documentación GitHub despliegue aplicación Node.js en Azure: https://docs.github.com/en/actions/use-cases-and-examples/deploying/deploying-nodejs-to-azure-app-service
# Ejemplos Actions específicas sobre Azure: https://github.com/Azure/actions-workflow-samples


# IMPORTANTE, esto no aparece en la documentación: En la configuración de Azure, una vez creado el App Service, añadir
# como comando de inicio: pm2 serve /home/site/wwwroot --no-daemon --spa
# PM2 es un servidor de producción para webs estáticas, no estamos sirviendo una aplicación javascript directamente.

name: Despliegue en Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: demogactweb        # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'        # set this to the path to your web app project, defaults to the repository root

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.18.0'  # Cambia a la versión de Node.js que utilices

    - name: npm install, build, and test
      run: |
        cd $GITHUB_WORKSPACE/app
        npm install
        npm run build
        ls -al ./build

    - name: Sube el directorio build 
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: ./app/build/
  
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build # Fuerza espera del build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
    steps:
    - name: Descarga artefacto del build
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: Mostrar archivos descargados
      run: |
        ls -al

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp        
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  
